[options]
girs_directories = ["../gir-files", "../webkit-gir-files"]
library = "JavaScriptCore"
version = "6.0"
min_cfg_version = "2.40.0"
work_mode = "normal"
target_path = "."
generate_safety_asserts = true
single_version_file = true

generate = [
    "JavaScriptCore.Context",
    "JavaScriptCore.CheckSyntaxMode",
    "JavaScriptCore.CheckSyntaxResult",
    "JavaScriptCore.Value",
    "JavaScriptCore.Class",
    # "JavaScriptCore.ClassVTable",
    "JavaScriptCore.VirtualMachine",
    "JavaScriptCore.Exception",
    "JavaScriptCore.WeakValue",
    "JavaScriptCore.ValuePropertyFlags",
    "JavaScriptCore.TypedArrayType",
    "JavaScriptCore.OptionType",
    "JavaScriptCore.ExceptionHandler",
]

manual = [
    "GLib.Bytes"
]

ignore = [
    "JavaScriptCore.ClassSetPropertyFunction",
    "JavaScriptCore.ClassHasPropertyFunction",
    "JavaScriptCore.ClassGetPropertyFunction",
    "JavaScriptCore.ClassEnumeratePropertiesFunction",
    "JavaScriptCore.ClassDeletePropertyFunction"
]