[crate_name_overrides]
"java_script_core" = "javascriptcore"

[options]
generate_safety_asserts = true
girs_directories = ["../gir-files", "../webkit-gir-files"]
library = "WebKit"
single_version_file = true
target_path = "."
version = "6.0"
min_cfg_version = "2.40.0"
work_mode = "normal"
use_gi_docgen = true

generate = [
  "WebKit.*",
  "WebKit.ApplicationInfo",
  "WebKit.Credential",
  "WebKit.AuthenticationScheme",
  "WebKit.SecurityOrigin",
  "WebKit.AutomationBrowsingContextPresentation",
  "WebKit.AutomationSession",
  "WebKit.WebView",
  "WebKit.AutoplayPolicy",
  "WebKit.BackForwardListItem",
  "WebKit.BackForwardList",
  "WebKit.CacheModel",
  "WebKit.PermissionRequest",
  "WebKit.ClipboardPermissionRequest",
  "WebKit.ColorChooserRequest",
  "WebKit.ContextMenu",
  "WebKit.ContextMenuItem",
  "WebKit.ContextMenuAction",
  "WebKit.CookieAcceptPolicy",
  "WebKit.CookiePersistentStorage",
  "WebKit.CredentialPersistence",
  "WebKit.DeviceInfoPermissionRequest",
  "WebKit.Download",
  "WebKit.URIRequest",
  "WebKit.URIResponse",
  "WebKit.DownloadError",
  "WebKit.EditorState",
  "WebKit.EditorTypingAttributes",
  "WebKit.FaviconDatabase",
  "WebKit.FaviconDatabaseError",
  "WebKit.FileChooserRequest",
  "WebKit.FindController",
  "WebKit.FindOptions",
  "WebKit.FormSubmissionRequest",
  "WebKit.GeolocationManager",
  "WebKit.GeolocationPosition",
  "WebKit.GeolocationPermissionRequest",
  "WebKit.HardwareAccelerationPolicy",
  "WebKit.HitTestResult",
  "WebKit.HitTestResultContext",
  "WebKit.ITPFirstParty",
  "WebKit.ITPThirdParty",
  "WebKit.InputHints",
  "WebKit.InputMethodContext",
  "WebKit.InputPurpose",
  "WebKit.InputMethodUnderline",
  "WebKit.InsecureContentEvent",
  "WebKit.JavascriptError",
  "WebKit.LoadEvent",
  "WebKit.MediaCaptureState",
  "WebKit.MediaError",
  "WebKit.MediaKeySystemPermissionRequest",
  "WebKit.MemoryPressureSettings",
  "WebKit.NavigationAction",
  "WebKit.NavigationType",
  "WebKit.NavigationPolicyDecision",
  "WebKit.PolicyDecision",
  "WebKit.NetworkError",
  "WebKit.NetworkProxyMode",
  "WebKit.NetworkProxySettings",
  "WebKit.TLSErrorsPolicy",
  "WebKit.Notification",
  "WebKit.NotificationPermissionRequest",
  "WebKit.OptionMenu",
  "WebKit.OptionMenuItem",
  "WebKit.PermissionState",
  "WebKit.PermissionStateQuery",
  "WebKit.PointerLockPermissionRequest",
  "WebKit.WebsitePolicies",
  "WebKit.PolicyDecisionType",
  "WebKit.PolicyError",
  "WebKit.PrintError",
  "WebKit.PrintOperation",
  "WebKit.PrintOperationResponse",
  "WebKit.ResponsePolicyDecision",
  "WebKit.SaveMode",
  "WebKit.ScriptDialog",
  "WebKit.ScriptDialogType",
  "WebKit.ScriptMessageReply",
  "WebKit.SecurityManager",
  "WebKit.Settings",
  "WebKit.SnapshotError",
  "WebKit.SnapshotOptions",
  "WebKit.SnapshotRegion",
  "WebKit.URISchemeRequest",
  "WebKit.URISchemeResponse",
  "WebKit.UserContentFilter",
  "WebKit.UserContentFilterError",
  "WebKit.UserContentInjectedFrames",
  "WebKit.UserContentManager",
  "WebKit.UserScript",
  "WebKit.UserStyleSheet",
  "WebKit.UserMediaPermissionRequest",
  "WebKit.UserMessage",
  "WebKit.UserMessageError",
  "WebKit.UserScriptInjectionTime",
  "WebKit.UserStyleLevel",
  "WebKit.WebContext",
  "WebKit.WebExtensionMode",
  "WebKit.WebInspector",
  "WebKit.WebViewBase",
  "WebKit.WebProcessTerminationReason",
  "WebKit.WebResource",
  "WebKit.WebViewSessionState",
  "WebKit.WindowProperties",
  "WebKit.WebsiteData",
  "WebKit.WebsiteDataTypes",
  "WebKit.WebsiteDataAccessPermissionRequest",
]

manual = [
  "Gtk.Accessible",
  "Gtk.Buildable",
  "Gtk.ConstraintTarget",
  "Gtk.Widget",
  "GLib.Bytes",
  "Gdk.Rectangle",
  "Gio.Cancellable",
  "GLib.Variant",
  "Gio.File",
  "GLib.Error",
  "GLib.Quark",
  "Gio.InputStream",
  "Gdk.RGBA",
  "Gio.UnixFDList",
  "Soup.MessageHeaders",
  "JavaScriptCore.Value",
  "Gtk.Window",
  "Gtk.PageSetup",
  "Gtk.PrintSettings",
  "Gdk.Event",
  "GLib.DateTime",
  "Gtk.FileFilter",
  "Soup.Cookie",
  "Gio.Action",
  "Gio.TlsCertificate",
  "Gio.TlsCertificateFlags",
  "Gio.TlsPasswordFlags",
  "Gdk.Texture",
  "GLib.TimeSpan",
]

[[object]]
name = "WebKit.CookieManager"
status = "generate"
  [[object.function]]
  pattern = "(add|delete)_cookie"
    [[object.function.parameter]]
    name = "cookie"
    const = true

[[object]]
name = "WebKit.AuthenticationRequest"
status = "generate"
  [[object.function]]
  name = "authenticate"
    [[object.function.parameter]]
    name = "credential"
    const = true

[[object]]
name = "WebKit.NetworkSession"
status = "generate"
  [[object.function]]
  name = "set_proxy_settings"
    [[object.function.parameter]]
    name = "proxy_settings"
    const = true

[[object]]
name = "WebKit.UserContentFilterStore"
status = "generate"
  [[object.function]]
  name = "fetch_identifiers"
  ignore = true # expected struct `Vec`, found `*mut *mut i8`

[[object]]
name = "WebKit.WebsiteDataManager"
status = "generate"
  [[object.function]]
  name = "clear"
  ignore = true # expected `i64`, found struct `TimeSpan`
  [[object.function]]
  name = "remove"
  ignore = true # website_data` escapes the associated function body here
